
name: "env"
dependencies: 
  # Python
  - python=3.11
  # Package
  - adlfs
  - aenum
  - aiofiles
  - aiohttp>=3.8.1
  - airflow==2.7.3
  - apache-airflow-providers-cncf-kubernetes
  - apache-airflow-providers-common-sql
  - apache-airflow-providers-slack>=7.1.0
  - apscheduler
  - asgiref
  - asyncssh
  - async-lru>=2.0.2
  - attrs>=22.2.0
  - autopep8>=1.6.0
  - azure-storage-blob>=12.18.1
  - black=23.3.0
  - boto3
  - catboost
  - cloudpickle
  - cryptography>=41.0.3
  - cvxopt
  - cvxpy>=1.3
  - conda-pack>=0.7.1
  - cppyy
  - dash>=2.13.0
  - dash-bootstrap-components
  - fastapi
  - flake8=5.0.4
  - freezegun
  - frozendict
  - ftputil
  - furo=2023.7.26
  - gitpython
  - go
  - graphviz
  - grpcio
  - humanize
  - hvac
  - ibis-framework
  - influxdb-client>=1.36.1
  - invoke>=2.2.0
  - ipdb
  - isort=5.12.0
  - jinja2
  - joblib
  - jupyter
  - jupyter-dash>=0.4.2
  - jupyter-resource-usage
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_server
  - jupyterhub
  - jupyterlab
  - jupyterlab-git
  - jupyterlab_execute_time
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - ldap
  - lmfit
  - matplotlib
  - maturin
  - memray
  - nbstripout
  - networkx
  - numba
  - numpy>=1.23.4
  - openssl==3.1.4
  - openai
  - pandas>=2.1.4
  - pandas_market_calendars>=4.1.4
  - paramiko
  - parquet-tools
  - plotly
  - plotnine
  - polars
  - pre_commit
  - psycopg2
  - pyarrow>=14.0.0
  - pybind11
  - py-spy
  - pydantic
  - pydot
  - pyflyby
  - pymssql
  - pyodbc
  - python-confluent-kafka
  - pytest-asyncio
  - pytest-cov
  - pytest-memray
  - pytest-xdist>=1.20.0
  - pytest>=7.1.2
  - python-dotenv
  - python-duckdb
  - python-graphviz
  - python-kubernetes
  - pyzmq>=23.2.0
  - ray-all==2.9.1
  - redis-py>=5.0.0
  - requests
  - rich
  - rustworkx
  - scikit-learn>=1.3.0
  - scipy>=1.10.1
  - seaborn
  - setuptools-rust
 